"use client";

import type { Metadata } from "next";
import { usePathname } from "next/navigation";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { GiConversation } from "react-icons/gi";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Elderly Care Robot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const hideChatButtonOn = ["/", "/chat"];
  const shouldHide = hideChatButtonOn.includes(pathname);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {!shouldHide && (<Link
            href="/chat"
            className="
                fixed bottom-6 right-6 
                w-40 h-40 
                bg-[#202A44] 
                text-white 
                rounded-full 
                shadow-xl 
                flex items-center justify-center 
                cursor-pointer 
                hover:scale-105 
                transition-transform
                z-50
            "
        >
            <GiConversation size={100} />
        </Link>
      )}
      </body>
    </html>
  );
}
